Added installation script for emacs25

diff --git a/functions/install_functions b/functions/install_functions
--- a/functions/install_functions
+++ b/functions/install_functions
@@ -87,6 +87,35 @@ function install_remote_package() {
 	fi
 }
 
+# Install from list function (non-interactive)
+#
+# ${1} = Name
+# ${2} = list-name
+
+function do_install_from_list() {
+    # Variables
+    LIST=${SCRIPT_DIR}'/data/'${2}'.list'
+    # Install loop
+    for PACKAGE in $(cat $LIST); do
+        # If package is not installed
+        if [ $(check_package_installed $PACKAGE) != 0 ]; then
+            # Install package
+            echo_message warning "Package '$PACKAGE' is not installed. Installing..."
+            # Admin privileges
+            superuser_do "apt install -y $PACKAGE"
+            # Check if failed
+            if [[ $? != 0 ]]; then
+                echo_message error "Error installing '$PACKAGE'."
+            fi
+        else
+            # Show already installed message
+            echo_message info "Package '$PACKAGE' is installed."
+        fi
+    done
+    # Finished
+    echo_message success "Installation of ${1} complete."
+}
+
 # Install from list function
 #
 # ${1} = Name
@@ -97,7 +126,7 @@ function install_from_list() {
 	# echo_message header "Starting 'install_from_list' function..."
 	echo_message title "Starting installation of ${1}..."
 	# Variables
-	LIST=$(dirname "$0")'/data/'${2}'.list'
+	LIST=${SCRIPT_DIR}'/data/'${2}'.list'
 	# Draw window
 	if (eval `resize` && whiptail \
 		--title "Install ${2^}" \
@@ -105,25 +134,7 @@ function install_from_list() {
 		$LINES $COLUMNS $(( $LINES - 12 )) \
 		--scrolltext \
 		3>&1 1>&2 2>&3) then
-		# Install loop
-		for PACKAGE in $(cat $LIST); do
-			# If package is not installed
-			if [ $(check_package_installed $PACKAGE) != 0 ]; then
-				# Install package
-				echo_message warning "Package '$PACKAGE' is not installed. Installing..."
-				# Admin privileges
-				superuser_do "apt install -y $PACKAGE"
-				# Check if failed
-				if [[ $? != 0 ]]; then
-					echo_message error "Error installing '$PACKAGE'."
-				fi
-			else
-				# Show already installed message
-				echo_message info "Package '$PACKAGE' is installed."
-			fi
-		done
-		# Finished
-		echo_message success "Installation of ${1} complete."
+		do_install_from_list $@
 		whiptail --title "Finished" --msgbox "Installation of ${1} is complete." 8 56
 		${3}
 	else
